/* Emacs style mode select   -*- C++ -*-
 *-----------------------------------------------------------------------------
 *
 *
 *  PrBoom: a Doom port merged with LxDoom and LSDLDoom
 *  based on BOOM, a modified and improved DOOM engine
 *  Copyright (C) 1999 by
 *  id Software, Chi Hoang, Lee Killough, Jim Flynn, Rand Phares, Ty Halderman
 *  Copyright (C) 1999-2000 by
 *  Jess Haas, Nicolas Kalkhof, Colin Phipps, Florian Schulze
 *  Copyright 2005, 2006 by
 *  Florian Schulze, Colin Phipps, Neil Stevens, Andrey Budko
 *  Copyright 2023, 2024 by
 *  Frenkel Smeijers
 *
 *  This program is free software; you can redistribute it and/or
 *  modify it under the terms of the GNU General Public License
 *  as published by the Free Software Foundation; either version 2
 *  of the License, or (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with this program; if not, write to the Free Software
 *  Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA
 *  02111-1307, USA.
 *
 * DESCRIPTION:
 *  Thing frame/state LUT,
 *  generated by multigen utilitiy.
 *  This one is the original DOOM version, preserved.
 *  BOOM changes include commenting and addition of predefined lumps
 *  for providing things that aren't in the IWAD without sending a
 *  separate must-use wad file around with the EXE.
 *
 *-----------------------------------------------------------------------------
 */

#include "doomdef.h"
#include "sounds.h"
#include "m_fixed.h"
#include "p_mobj.h"
#include "p_enemy.h"
#include "p_pspr.h"
#include "w_wad.h"
#include "info.h"


// ********************************************************************
// Sprite names
// ********************************************************************
// This is the list of sprite 4-character prefixes.  They are searched
// through.
// NUMSPRITES is an enum from info.h where all these are listed
// as SPR_xxxx

const char * const sprnames[NUMSPRITES] = {
  "TROO","SHTG","PUNG","PISG","PISF","SHTF","CHGG","CHGF","MISG",
  "MISF","SAWG","BLUD","PUFF","BAL1",
  "MISL","TFOG","PLAY","POSS",
  "SPOS","SARG",
  "BAL7","BOSS",
  "ARM1","ARM2","BAR1","BEXP",
  "BON1","BON2","BKEY","RKEY","YKEY","STIM","MEDI",
  "SOUL","PINS","SUIT","PMAP","PVIS","CLIP","AMMO",
  "ROCK","BROK","SHEL","SBOX","BPAK","MGUN","CSAW",
  "LAUN","SHOT","COLU","POL5",
  "CAND","CBRA","ELEC",
  "TRED"
};

// ********************************************************************
// State or "frame" information
// ********************************************************************
// Each of the states, otherwise known as "frames", is outlined
// here.  The data in each element of the array is the way it is
// initialized, with sprite names identified by their enumerator
// value such as SPR_SHTG.  These correlate to the above sprite
// array so don't change them around unless you understand what
// you're doing.
//
// The commented name beginning with S_ at the end of each line
// is there to help figure out where the next-frame pointer is
// pointing.  These are also additionally identified in info.h
// as enumerated values.  From a change-and-recompile point of
// view this is fairly workable, but it adds a lot to the effort
// when trying to change things externally.  See also the d_deh.c
// parts where frame rewiring is done for more details and the
// extended way a BEX file can handle this.

const state_t states[NUMSTATES] = {
  {SPR_TROO,0,-1,NULL,S_NULL},  // S_NULL
  {SPR_SHTG,4,0,A_Light0,S_NULL}, // S_LIGHTDONE
  {SPR_PUNG,0,1,A_WeaponReady,S_PUNCH}, // S_PUNCH
  {SPR_PUNG,0,1,A_Lower,S_PUNCHDOWN}, // S_PUNCHDOWN
  {SPR_PUNG,0,1,A_Raise,S_PUNCHUP}, // S_PUNCHUP
  {SPR_PUNG,1,4,NULL,S_PUNCH2},   // S_PUNCH1
  {SPR_PUNG,2,4,A_Punch,S_PUNCH3},  // S_PUNCH2
  {SPR_PUNG,3,5,NULL,S_PUNCH4},   // S_PUNCH3
  {SPR_PUNG,2,4,NULL,S_PUNCH5},   // S_PUNCH4
  {SPR_PUNG,1,5,A_ReFire,S_PUNCH},  // S_PUNCH5
  {SPR_PISG,0,1,A_WeaponReady,S_PISTOL},// S_PISTOL
  {SPR_PISG,0,1,A_Lower,S_PISTOLDOWN},  // S_PISTOLDOWN
  {SPR_PISG,0,1,A_Raise,S_PISTOLUP},  // S_PISTOLUP
  {SPR_PISG,0,4,NULL,S_PISTOL2},  // S_PISTOL1
  {SPR_PISG,1,6,A_FirePistol,S_PISTOL3},// S_PISTOL2
  {SPR_PISG,2,4,NULL,S_PISTOL4},  // S_PISTOL3
  {SPR_PISG,1,5,A_ReFire,S_PISTOL}, // S_PISTOL4
  {SPR_PISF,32768,7,A_Light1,S_LIGHTDONE},  // S_PISTOLFLASH
  {SPR_SHTG,0,1,A_WeaponReady,S_SGUN},  // S_SGUN
  {SPR_SHTG,0,1,A_Lower,S_SGUNDOWN},  // S_SGUNDOWN
  {SPR_SHTG,0,1,A_Raise,S_SGUNUP},  // S_SGUNUP
  {SPR_SHTG,0,3,NULL,S_SGUN2},  // S_SGUN1
  {SPR_SHTG,0,7,A_FireShotgun,S_SGUN3}, // S_SGUN2
  {SPR_SHTG,1,5,NULL,S_SGUN4},  // S_SGUN3
  {SPR_SHTG,2,5,NULL,S_SGUN5},  // S_SGUN4
  {SPR_SHTG,3,4,NULL,S_SGUN6},  // S_SGUN5
  {SPR_SHTG,2,5,NULL,S_SGUN7},  // S_SGUN6
  {SPR_SHTG,1,5,NULL,S_SGUN8},  // S_SGUN7
  {SPR_SHTG,0,3,NULL,S_SGUN9},  // S_SGUN8
  {SPR_SHTG,0,7,A_ReFire,S_SGUN}, // S_SGUN9
  {SPR_SHTF,32768,4,A_Light1,S_SGUNFLASH2}, // S_SGUNFLASH1
  {SPR_SHTF,32769,3,A_Light2,S_LIGHTDONE},  // S_SGUNFLASH2
  {SPR_CHGG,0,1,A_WeaponReady,S_CHAIN}, // S_CHAIN
  {SPR_CHGG,0,1,A_Lower,S_CHAINDOWN}, // S_CHAINDOWN
  {SPR_CHGG,0,1,A_Raise,S_CHAINUP}, // S_CHAINUP
  {SPR_CHGG,0,4,A_FireCGun,S_CHAIN2}, // S_CHAIN1
  {SPR_CHGG,1,4,A_FireCGun,S_CHAIN3}, // S_CHAIN2
  {SPR_CHGG,1,0,A_ReFire,S_CHAIN},  // S_CHAIN3
  {SPR_CHGF,32768,5,A_Light1,S_LIGHTDONE},  // S_CHAINFLASH1
  {SPR_CHGF,32769,5,A_Light2,S_LIGHTDONE},  // S_CHAINFLASH2
  {SPR_MISG,0,1,A_WeaponReady,S_MISSILE}, // S_MISSILE
  {SPR_MISG,0,1,A_Lower,S_MISSILEDOWN}, // S_MISSILEDOWN
  {SPR_MISG,0,1,A_Raise,S_MISSILEUP}, // S_MISSILEUP
  {SPR_MISG,1,8,A_GunFlash,S_MISSILE2}, // S_MISSILE1
  {SPR_MISG,1,12,A_FireMissile,S_MISSILE3}, // S_MISSILE2
  {SPR_MISG,1,0,A_ReFire,S_MISSILE},  // S_MISSILE3
  {SPR_MISF,32768,3,A_Light1,S_MISSILEFLASH2},  // S_MISSILEFLASH1
  {SPR_MISF,32769,4,NULL,S_MISSILEFLASH3},  // S_MISSILEFLASH2
  {SPR_MISF,32770,4,A_Light2,S_MISSILEFLASH4},  // S_MISSILEFLASH3
  {SPR_MISF,32771,4,A_Light2,S_LIGHTDONE},  // S_MISSILEFLASH4
  {SPR_SAWG,2,4,A_WeaponReady,S_SAWB},  // S_SAW
  {SPR_SAWG,3,4,A_WeaponReady,S_SAW}, // S_SAWB
  {SPR_SAWG,2,1,A_Lower,S_SAWDOWN}, // S_SAWDOWN
  {SPR_SAWG,2,1,A_Raise,S_SAWUP}, // S_SAWUP
  {SPR_SAWG,0,4,A_Saw,S_SAW2}, // S_SAW1
  {SPR_SAWG,1,4,A_Saw,S_SAW3},  // S_SAW2
  {SPR_SAWG,1,0,A_ReFire,S_SAW},  // S_SAW3
  {SPR_BLUD,2,8,NULL,S_BLOOD2}, // S_BLOOD1
  {SPR_BLUD,1,8,NULL,S_BLOOD3}, // S_BLOOD2
  {SPR_BLUD,0,8,NULL,S_NULL}, // S_BLOOD3
  {SPR_PUFF,32768,4,NULL,S_PUFF2},  // S_PUFF1
  {SPR_PUFF,1,4,NULL,S_PUFF3},  // S_PUFF2
  {SPR_PUFF,2,4,NULL,S_PUFF4},  // S_PUFF3
  {SPR_PUFF,3,4,NULL,S_NULL}, // S_PUFF4
  {SPR_BAL1,32768,4,NULL,S_TBALL2}, // S_TBALL1
  {SPR_BAL1,32769,4,NULL,S_TBALL1}, // S_TBALL2
  {SPR_BAL1,32770,6,NULL,S_TBALLX2},  // S_TBALLX1
  {SPR_BAL1,32771,6,NULL,S_TBALLX3},  // S_TBALLX2
  {SPR_BAL1,32772,6,NULL,S_NULL}, // S_TBALLX3
  {SPR_MISL,32768,1,NULL,S_ROCKET}, // S_ROCKET
  {SPR_MISL,32769,8,A_Explode,S_EXPLODE2},  // S_EXPLODE1
  {SPR_MISL,32770,6,NULL,S_EXPLODE3}, // S_EXPLODE2
  {SPR_MISL,32771,4,NULL,S_NULL}, // S_EXPLODE3
  {SPR_TFOG,32768,6,NULL,S_TFOG01}, // S_TFOG
  {SPR_TFOG,32769,6,NULL,S_TFOG02}, // S_TFOG01
  {SPR_TFOG,32768,6,NULL,S_TFOG2},  // S_TFOG02
  {SPR_TFOG,32769,6,NULL,S_TFOG3},  // S_TFOG2
  {SPR_TFOG,32770,6,NULL,S_TFOG4},  // S_TFOG3
  {SPR_TFOG,32771,6,NULL,S_TFOG5},  // S_TFOG4
  {SPR_TFOG,32772,6,NULL,S_TFOG6},  // S_TFOG5
  {SPR_TFOG,32773,6,NULL,S_TFOG7},  // S_TFOG6
  {SPR_TFOG,32774,6,NULL,S_TFOG8},  // S_TFOG7
  {SPR_TFOG,32775,6,NULL,S_TFOG9},  // S_TFOG8
  {SPR_TFOG,32776,6,NULL,S_TFOG10}, // S_TFOG9
  {SPR_TFOG,32777,6,NULL,S_NULL}, // S_TFOG10
  {SPR_PLAY,0,-1,NULL,S_NULL},  // S_PLAY
  {SPR_PLAY,0,4,NULL,S_PLAY_RUN2},  // S_PLAY_RUN1
  {SPR_PLAY,1,4,NULL,S_PLAY_RUN3},  // S_PLAY_RUN2
  {SPR_PLAY,2,4,NULL,S_PLAY_RUN4},  // S_PLAY_RUN3
  {SPR_PLAY,3,4,NULL,S_PLAY_RUN1},  // S_PLAY_RUN4
  {SPR_PLAY,4,12,NULL,S_PLAY},  // S_PLAY_ATK1
  {SPR_PLAY,32773,6,NULL,S_PLAY_ATK1},  // S_PLAY_ATK2
  {SPR_PLAY,6,4,NULL,S_PLAY_PAIN2}, // S_PLAY_PAIN
  {SPR_PLAY,6,4,A_Pain,S_PLAY}, // S_PLAY_PAIN2
  {SPR_PLAY,7,10,NULL,S_PLAY_DIE2}, // S_PLAY_DIE1
  {SPR_PLAY,8,10,A_PlayerScream,S_PLAY_DIE3}, // S_PLAY_DIE2
  {SPR_PLAY,9,10,A_Fall,S_PLAY_DIE4}, // S_PLAY_DIE3
  {SPR_PLAY,10,10,NULL,S_PLAY_DIE5},  // S_PLAY_DIE4
  {SPR_PLAY,11,10,NULL,S_PLAY_DIE6},  // S_PLAY_DIE5
  {SPR_PLAY,12,10,NULL,S_PLAY_DIE7},  // S_PLAY_DIE6
  {SPR_PLAY,13,-1,NULL,S_NULL}, // S_PLAY_DIE7
  {SPR_PLAY,14,5,NULL,S_PLAY_XDIE2},  // S_PLAY_XDIE1
  {SPR_PLAY,15,5,A_XScream,S_PLAY_XDIE3}, // S_PLAY_XDIE2
  {SPR_PLAY,16,5,A_Fall,S_PLAY_XDIE4},  // S_PLAY_XDIE3
  {SPR_PLAY,17,5,NULL,S_PLAY_XDIE5},  // S_PLAY_XDIE4
  {SPR_PLAY,18,5,NULL,S_PLAY_XDIE6},  // S_PLAY_XDIE5
  {SPR_PLAY,19,5,NULL,S_PLAY_XDIE7},  // S_PLAY_XDIE6
  {SPR_PLAY,20,5,NULL,S_PLAY_XDIE8},  // S_PLAY_XDIE7
  {SPR_PLAY,21,5,NULL,S_PLAY_XDIE9},  // S_PLAY_XDIE8
  {SPR_PLAY,22,-1,NULL,S_NULL}, // S_PLAY_XDIE9
  {SPR_POSS,0,10,A_Look,S_POSS_STND2},  // S_POSS_STND
  {SPR_POSS,1,10,A_Look,S_POSS_STND}, // S_POSS_STND2
  {SPR_POSS,0,4,A_Chase,S_POSS_RUN2}, // S_POSS_RUN1
  {SPR_POSS,0,4,A_Chase,S_POSS_RUN3}, // S_POSS_RUN2
  {SPR_POSS,1,4,A_Chase,S_POSS_RUN4}, // S_POSS_RUN3
  {SPR_POSS,1,4,A_Chase,S_POSS_RUN5}, // S_POSS_RUN4
  {SPR_POSS,2,4,A_Chase,S_POSS_RUN6}, // S_POSS_RUN5
  {SPR_POSS,2,4,A_Chase,S_POSS_RUN7}, // S_POSS_RUN6
  {SPR_POSS,3,4,A_Chase,S_POSS_RUN8}, // S_POSS_RUN7
  {SPR_POSS,3,4,A_Chase,S_POSS_RUN1}, // S_POSS_RUN8
  {SPR_POSS,4,10,A_FaceTarget,S_POSS_ATK2}, // S_POSS_ATK1
  {SPR_POSS,5,8,A_PosAttack,S_POSS_ATK3}, // S_POSS_ATK2
  {SPR_POSS,4,8,NULL,S_POSS_RUN1},  // S_POSS_ATK3
  {SPR_POSS,6,3,NULL,S_POSS_PAIN2}, // S_POSS_PAIN
  {SPR_POSS,6,3,A_Pain,S_POSS_RUN1},  // S_POSS_PAIN2
  {SPR_POSS,7,5,NULL,S_POSS_DIE2},  // S_POSS_DIE1
  {SPR_POSS,8,5,A_Scream,S_POSS_DIE3},  // S_POSS_DIE2
  {SPR_POSS,9,5,A_Fall,S_POSS_DIE4},  // S_POSS_DIE3
  {SPR_POSS,10,5,NULL,S_POSS_DIE5}, // S_POSS_DIE4
  {SPR_POSS,11,-1,NULL,S_NULL}, // S_POSS_DIE5
  {SPR_POSS,12,5,NULL,S_POSS_XDIE2},  // S_POSS_XDIE1
  {SPR_POSS,13,5,A_XScream,S_POSS_XDIE3}, // S_POSS_XDIE2
  {SPR_POSS,14,5,A_Fall,S_POSS_XDIE4},  // S_POSS_XDIE3
  {SPR_POSS,15,5,NULL,S_POSS_XDIE5},  // S_POSS_XDIE4
  {SPR_POSS,16,5,NULL,S_POSS_XDIE6},  // S_POSS_XDIE5
  {SPR_POSS,17,5,NULL,S_POSS_XDIE7},  // S_POSS_XDIE6
  {SPR_POSS,18,5,NULL,S_POSS_XDIE8},  // S_POSS_XDIE7
  {SPR_POSS,19,5,NULL,S_POSS_XDIE9},  // S_POSS_XDIE8
  {SPR_POSS,20,-1,NULL,S_NULL}, // S_POSS_XDIE9
  {SPR_SPOS,0,10,A_Look,S_SPOS_STND2},  // S_SPOS_STND
  {SPR_SPOS,1,10,A_Look,S_SPOS_STND}, // S_SPOS_STND2
  {SPR_SPOS,0,3,A_Chase,S_SPOS_RUN2}, // S_SPOS_RUN1
  {SPR_SPOS,0,3,A_Chase,S_SPOS_RUN3}, // S_SPOS_RUN2
  {SPR_SPOS,1,3,A_Chase,S_SPOS_RUN4}, // S_SPOS_RUN3
  {SPR_SPOS,1,3,A_Chase,S_SPOS_RUN5}, // S_SPOS_RUN4
  {SPR_SPOS,2,3,A_Chase,S_SPOS_RUN6}, // S_SPOS_RUN5
  {SPR_SPOS,2,3,A_Chase,S_SPOS_RUN7}, // S_SPOS_RUN6
  {SPR_SPOS,3,3,A_Chase,S_SPOS_RUN8}, // S_SPOS_RUN7
  {SPR_SPOS,3,3,A_Chase,S_SPOS_RUN1}, // S_SPOS_RUN8
  {SPR_SPOS,4,10,A_FaceTarget,S_SPOS_ATK2}, // S_SPOS_ATK1
  {SPR_SPOS,32773,10,A_SPosAttack,S_SPOS_ATK3}, // S_SPOS_ATK2
  {SPR_SPOS,4,10,NULL,S_SPOS_RUN1}, // S_SPOS_ATK3
  {SPR_SPOS,6,3,NULL,S_SPOS_PAIN2}, // S_SPOS_PAIN
  {SPR_SPOS,6,3,A_Pain,S_SPOS_RUN1},  // S_SPOS_PAIN2
  {SPR_SPOS,7,5,NULL,S_SPOS_DIE2},  // S_SPOS_DIE1
  {SPR_SPOS,8,5,A_Scream,S_SPOS_DIE3},  // S_SPOS_DIE2
  {SPR_SPOS,9,5,A_Fall,S_SPOS_DIE4},  // S_SPOS_DIE3
  {SPR_SPOS,10,5,NULL,S_SPOS_DIE5}, // S_SPOS_DIE4
  {SPR_SPOS,11,-1,NULL,S_NULL}, // S_SPOS_DIE5
  {SPR_SPOS,12,5,NULL,S_SPOS_XDIE2},  // S_SPOS_XDIE1
  {SPR_SPOS,13,5,A_XScream,S_SPOS_XDIE3}, // S_SPOS_XDIE2
  {SPR_SPOS,14,5,A_Fall,S_SPOS_XDIE4},  // S_SPOS_XDIE3
  {SPR_SPOS,15,5,NULL,S_SPOS_XDIE5},  // S_SPOS_XDIE4
  {SPR_SPOS,16,5,NULL,S_SPOS_XDIE6},  // S_SPOS_XDIE5
  {SPR_SPOS,17,5,NULL,S_SPOS_XDIE7},  // S_SPOS_XDIE6
  {SPR_SPOS,18,5,NULL,S_SPOS_XDIE8},  // S_SPOS_XDIE7
  {SPR_SPOS,19,5,NULL,S_SPOS_XDIE9},  // S_SPOS_XDIE8
  {SPR_SPOS,20,-1,NULL,S_NULL}, // S_SPOS_XDIE9
  {SPR_TROO,0,10,A_Look,S_TROO_STND2},  // S_TROO_STND
  {SPR_TROO,1,10,A_Look,S_TROO_STND}, // S_TROO_STND2
  {SPR_TROO,0,3,A_Chase,S_TROO_RUN2}, // S_TROO_RUN1
  {SPR_TROO,0,3,A_Chase,S_TROO_RUN3}, // S_TROO_RUN2
  {SPR_TROO,1,3,A_Chase,S_TROO_RUN4}, // S_TROO_RUN3
  {SPR_TROO,1,3,A_Chase,S_TROO_RUN5}, // S_TROO_RUN4
  {SPR_TROO,2,3,A_Chase,S_TROO_RUN6}, // S_TROO_RUN5
  {SPR_TROO,2,3,A_Chase,S_TROO_RUN7}, // S_TROO_RUN6
  {SPR_TROO,3,3,A_Chase,S_TROO_RUN8}, // S_TROO_RUN7
  {SPR_TROO,3,3,A_Chase,S_TROO_RUN1}, // S_TROO_RUN8
  {SPR_TROO,4,8,A_FaceTarget,S_TROO_ATK2},  // S_TROO_ATK1
  {SPR_TROO,5,8,A_FaceTarget,S_TROO_ATK3},  // S_TROO_ATK2
  {SPR_TROO,6,6,A_TroopAttack,S_TROO_RUN1}, // S_TROO_ATK3
  {SPR_TROO,7,2,NULL,S_TROO_PAIN2}, // S_TROO_PAIN
  {SPR_TROO,7,2,A_Pain,S_TROO_RUN1},  // S_TROO_PAIN2
  {SPR_TROO,8,8,NULL,S_TROO_DIE2},  // S_TROO_DIE1
  {SPR_TROO,9,8,A_Scream,S_TROO_DIE3},  // S_TROO_DIE2
  {SPR_TROO,10,6,NULL,S_TROO_DIE4}, // S_TROO_DIE3
  {SPR_TROO,11,6,A_Fall,S_TROO_DIE5}, // S_TROO_DIE4
  {SPR_TROO,12,-1,NULL,S_NULL}, // S_TROO_DIE5
  {SPR_TROO,13,5,NULL,S_TROO_XDIE2},  // S_TROO_XDIE1
  {SPR_TROO,14,5,A_XScream,S_TROO_XDIE3}, // S_TROO_XDIE2
  {SPR_TROO,15,5,NULL,S_TROO_XDIE4},  // S_TROO_XDIE3
  {SPR_TROO,16,5,A_Fall,S_TROO_XDIE5},  // S_TROO_XDIE4
  {SPR_TROO,17,5,NULL,S_TROO_XDIE6},  // S_TROO_XDIE5
  {SPR_TROO,18,5,NULL,S_TROO_XDIE7},  // S_TROO_XDIE6
  {SPR_TROO,19,5,NULL,S_TROO_XDIE8},  // S_TROO_XDIE7
  {SPR_TROO,20,-1,NULL,S_NULL}, // S_TROO_XDIE8
  {SPR_SARG,0,10,A_Look,S_SARG_STND2},  // S_SARG_STND
  {SPR_SARG,1,10,A_Look,S_SARG_STND}, // S_SARG_STND2
  {SPR_SARG,0,2,A_Chase,S_SARG_RUN2}, // S_SARG_RUN1
  {SPR_SARG,0,2,A_Chase,S_SARG_RUN3}, // S_SARG_RUN2
  {SPR_SARG,1,2,A_Chase,S_SARG_RUN4}, // S_SARG_RUN3
  {SPR_SARG,1,2,A_Chase,S_SARG_RUN5}, // S_SARG_RUN4
  {SPR_SARG,2,2,A_Chase,S_SARG_RUN6}, // S_SARG_RUN5
  {SPR_SARG,2,2,A_Chase,S_SARG_RUN7}, // S_SARG_RUN6
  {SPR_SARG,3,2,A_Chase,S_SARG_RUN8}, // S_SARG_RUN7
  {SPR_SARG,3,2,A_Chase,S_SARG_RUN1}, // S_SARG_RUN8
  {SPR_SARG,4,8,A_FaceTarget,S_SARG_ATK2},  // S_SARG_ATK1
  {SPR_SARG,5,8,A_FaceTarget,S_SARG_ATK3},  // S_SARG_ATK2
  {SPR_SARG,6,8,A_SargAttack,S_SARG_RUN1},  // S_SARG_ATK3
  {SPR_SARG,7,2,NULL,S_SARG_PAIN2}, // S_SARG_PAIN
  {SPR_SARG,7,2,A_Pain,S_SARG_RUN1},  // S_SARG_PAIN2
  {SPR_SARG,8,8,NULL,S_SARG_DIE2},  // S_SARG_DIE1
  {SPR_SARG,9,8,A_Scream,S_SARG_DIE3},  // S_SARG_DIE2
  {SPR_SARG,10,4,NULL,S_SARG_DIE4}, // S_SARG_DIE3
  {SPR_SARG,11,4,A_Fall,S_SARG_DIE5}, // S_SARG_DIE4
  {SPR_SARG,12,4,NULL,S_SARG_DIE6}, // S_SARG_DIE5
  {SPR_SARG,13,-1,NULL,S_NULL}, // S_SARG_DIE6
  {SPR_BAL7,32768,4,NULL,S_BRBALL2},  // S_BRBALL1
  {SPR_BAL7,32769,4,NULL,S_BRBALL1},  // S_BRBALL2
  {SPR_BAL7,32770,6,NULL,S_BRBALLX2}, // S_BRBALLX1
  {SPR_BAL7,32771,6,NULL,S_BRBALLX3}, // S_BRBALLX2
  {SPR_BAL7,32772,6,NULL,S_NULL}, // S_BRBALLX3
  {SPR_BOSS,0,10,A_Look,S_BOSS_STND2},  // S_BOSS_STND
  {SPR_BOSS,1,10,A_Look,S_BOSS_STND}, // S_BOSS_STND2
  {SPR_BOSS,0,3,A_Chase,S_BOSS_RUN2}, // S_BOSS_RUN1
  {SPR_BOSS,0,3,A_Chase,S_BOSS_RUN3}, // S_BOSS_RUN2
  {SPR_BOSS,1,3,A_Chase,S_BOSS_RUN4}, // S_BOSS_RUN3
  {SPR_BOSS,1,3,A_Chase,S_BOSS_RUN5}, // S_BOSS_RUN4
  {SPR_BOSS,2,3,A_Chase,S_BOSS_RUN6}, // S_BOSS_RUN5
  {SPR_BOSS,2,3,A_Chase,S_BOSS_RUN7}, // S_BOSS_RUN6
  {SPR_BOSS,3,3,A_Chase,S_BOSS_RUN8}, // S_BOSS_RUN7
  {SPR_BOSS,3,3,A_Chase,S_BOSS_RUN1}, // S_BOSS_RUN8
  {SPR_BOSS,4,8,A_FaceTarget,S_BOSS_ATK2},  // S_BOSS_ATK1
  {SPR_BOSS,5,8,A_FaceTarget,S_BOSS_ATK3},  // S_BOSS_ATK2
  {SPR_BOSS,6,8,A_BruisAttack,S_BOSS_RUN1}, // S_BOSS_ATK3
  {SPR_BOSS,7,2,NULL,S_BOSS_PAIN2}, // S_BOSS_PAIN
  {SPR_BOSS,7,2,A_Pain,S_BOSS_RUN1},  // S_BOSS_PAIN2
  {SPR_BOSS,8,8,NULL,S_BOSS_DIE2},  // S_BOSS_DIE1
  {SPR_BOSS,9,8,A_Scream,S_BOSS_DIE3},  // S_BOSS_DIE2
  {SPR_BOSS,10,8,NULL,S_BOSS_DIE4}, // S_BOSS_DIE3
  {SPR_BOSS,11,8,A_Fall,S_BOSS_DIE5}, // S_BOSS_DIE4
  {SPR_BOSS,12,8,NULL,S_BOSS_DIE6}, // S_BOSS_DIE5
  {SPR_BOSS,13,8,NULL,S_BOSS_DIE7}, // S_BOSS_DIE6
  {SPR_BOSS,14,-1,A_BossDeath,S_NULL},  // S_BOSS_DIE7
  {SPR_ARM1,0,6,NULL,S_ARM1A},  // S_ARM1
  {SPR_ARM1,32769,7,NULL,S_ARM1}, // S_ARM1A
  {SPR_ARM2,0,6,NULL,S_ARM2A},  // S_ARM2
  {SPR_ARM2,32769,6,NULL,S_ARM2}, // S_ARM2A
  {SPR_BAR1,0,6,NULL,S_BAR2}, // S_BAR1
  {SPR_BAR1,1,6,NULL,S_BAR1}, // S_BAR2
  {SPR_BEXP,32768,5,NULL,S_BEXP2},  // S_BEXP
  {SPR_BEXP,32769,5,A_Scream,S_BEXP3},  // S_BEXP2
  {SPR_BEXP,32770,5,NULL,S_BEXP4},  // S_BEXP3
  {SPR_BEXP,32771,10,A_Explode,S_BEXP5},  // S_BEXP4
  {SPR_BEXP,32772,10,NULL,S_NULL},  // S_BEXP5
  {SPR_BON1,0,6,NULL,S_BON1A},  // S_BON1
  {SPR_BON1,1,6,NULL,S_BON1B},  // S_BON1A
  {SPR_BON1,2,6,NULL,S_BON1C},  // S_BON1B
  {SPR_BON1,3,6,NULL,S_BON1D},  // S_BON1C
  {SPR_BON1,2,6,NULL,S_BON1E},  // S_BON1D
  {SPR_BON1,1,6,NULL,S_BON1}, // S_BON1E
  {SPR_BON2,0,6,NULL,S_BON2A},  // S_BON2
  {SPR_BON2,1,6,NULL,S_BON2B},  // S_BON2A
  {SPR_BON2,2,6,NULL,S_BON2C},  // S_BON2B
  {SPR_BON2,3,6,NULL,S_BON2D},  // S_BON2C
  {SPR_BON2,2,6,NULL,S_BON2E},  // S_BON2D
  {SPR_BON2,1,6,NULL,S_BON2}, // S_BON2E
  {SPR_BKEY,0,10,NULL,S_BKEY2}, // S_BKEY
  {SPR_BKEY,32769,10,NULL,S_BKEY},  // S_BKEY2
  {SPR_RKEY,0,10,NULL,S_RKEY2}, // S_RKEY
  {SPR_RKEY,32769,10,NULL,S_RKEY},  // S_RKEY2
  {SPR_YKEY,0,10,NULL,S_YKEY2}, // S_YKEY
  {SPR_YKEY,32769,10,NULL,S_YKEY},  // S_YKEY2
  {SPR_STIM,0,-1,NULL,S_NULL},  // S_STIM
  {SPR_MEDI,0,-1,NULL,S_NULL},  // S_MEDI
  {SPR_SOUL,32768,6,NULL,S_SOUL2},  // S_SOUL
  {SPR_SOUL,32769,6,NULL,S_SOUL3},  // S_SOUL2
  {SPR_SOUL,32770,6,NULL,S_SOUL4},  // S_SOUL3
  {SPR_SOUL,32771,6,NULL,S_SOUL5},  // S_SOUL4
  {SPR_SOUL,32770,6,NULL,S_SOUL6},  // S_SOUL5
  {SPR_SOUL,32769,6,NULL,S_SOUL}, // S_SOUL6
  {SPR_PINS,32768,6,NULL,S_PINS2},  // S_PINS
  {SPR_PINS,32769,6,NULL,S_PINS3},  // S_PINS2
  {SPR_PINS,32770,6,NULL,S_PINS4},  // S_PINS3
  {SPR_PINS,32771,6,NULL,S_PINS}, // S_PINS4
  {SPR_SUIT,32768,-1,NULL,S_NULL},  // S_SUIT
  {SPR_PMAP,32768,6,NULL,S_PMAP2},  // S_PMAP
  {SPR_PMAP,32769,6,NULL,S_PMAP3},  // S_PMAP2
  {SPR_PMAP,32770,6,NULL,S_PMAP4},  // S_PMAP3
  {SPR_PMAP,32771,6,NULL,S_PMAP5},  // S_PMAP4
  {SPR_PMAP,32770,6,NULL,S_PMAP6},  // S_PMAP5
  {SPR_PMAP,32769,6,NULL,S_PMAP}, // S_PMAP6
  {SPR_PVIS,32768,6,NULL,S_PVIS2},  // S_PVIS
  {SPR_PVIS,1,6,NULL,S_PVIS}, // S_PVIS2
  {SPR_CLIP,0,-1,NULL,S_NULL},  // S_CLIP
  {SPR_AMMO,0,-1,NULL,S_NULL},  // S_AMMO
  {SPR_ROCK,0,-1,NULL,S_NULL},  // S_ROCK
  {SPR_BROK,0,-1,NULL,S_NULL},  // S_BROK
  {SPR_SHEL,0,-1,NULL,S_NULL},  // S_SHEL
  {SPR_SBOX,0,-1,NULL,S_NULL},  // S_SBOX
  {SPR_BPAK,0,-1,NULL,S_NULL},  // S_BPAK
  {SPR_MGUN,0,-1,NULL,S_NULL},  // S_MGUN
  {SPR_CSAW,0,-1,NULL,S_NULL},  // S_CSAW
  {SPR_LAUN,0,-1,NULL,S_NULL},  // S_LAUN
  {SPR_SHOT,0,-1,NULL,S_NULL},  // S_SHOT
  {SPR_COLU,32768,-1,NULL,S_NULL},  // S_COLU
  {SPR_POL5,0,-1,NULL,S_NULL},	// S_GIBS
  {SPR_CAND,32768,-1,NULL,S_NULL},	// S_CANDLESTIK
  {SPR_CBRA,32768,-1,NULL,S_NULL},  // S_CANDELABRA
  {SPR_ELEC,0,-1,NULL,S_NULL},  // S_TECHPILLAR
  {SPR_TRED,32768,4,NULL,S_REDTORCH2},  // S_REDTORCH
  {SPR_TRED,32769,4,NULL,S_REDTORCH3},  // S_REDTORCH2
  {SPR_TRED,32770,4,NULL,S_REDTORCH4},  // S_REDTORCH3
  {SPR_TRED,32771,4,NULL,S_REDTORCH} // S_REDTORCH4
};

// ********************************************************************
// Object "Thing" definitions
// ********************************************************************
// Now we get to the actual objects and their characteristics.  If
// you've seen Dehacked, much of this is where the Bits are set,
// commented below as "flags", as well as where you wire in which
// frames are the beginning frames for near and far attack, death,
// and such.  Sounds are hooked in here too, as well as how much
// mass, speed and so forth a Thing has.  Everything you ever wanted
// to know...
//
// Like all this other stuff, the MT_* entries are enumerated in info.h
//
// Note that these are all just indices of the elements involved, and
// not real pointers to them.  For example, the player's death sequence
// is S_PLAY_DIE1, which just evaluates to the index in the states[]
// array above, which actually knows what happens then and what the
// sprite looks like, if it makes noise or not, etc.
//
// Additional comments about each of the entries are located in info.h
// next to the mobjinfo_t structure definition.
//
// This goes on for the next 3000+ lines...

const mobjinfo_t mobjinfo[NUMMOBJTYPES] = {
  {   // MT_PLAYER
    -1,   // doomednum
    S_PLAY,   // spawnstate
    100,    // spawnhealth
    S_PLAY_RUN1,    // seestate
    sfx_None,   // seesound
    0,    // reactiontime
    sfx_None,   // attacksound
    S_PLAY_PAIN,    // painstate
    255,    // painchance
    sfx_plpain,   // painsound
    S_NULL,   // meleestate
    S_PLAY_ATK1,    // missilestate
    S_PLAY_DIE1,    // deathstate
    S_PLAY_XDIE1,   // xdeathstate
    sfx_pldeth,   // deathsound
    0,    // speed
    16*FRACUNIT,    // radius
    56*FRACUNIT,    // height
    100,    // mass
    0,    // damage
    sfx_None,   // activesound
    MF_SOLID|MF_SHOOTABLE|MF_DROPOFF|MF_PICKUP    // flags
  },

  {   // MT_POSSESSED
    3004,   // doomednum
    S_POSS_STND,    // spawnstate
    20,   // spawnhealth
    S_POSS_RUN1,    // seestate
    sfx_posit1,   // seesound
    8,    // reactiontime
    sfx_pistol,   // attacksound
    S_POSS_PAIN,    // painstate
    200,    // painchance
    sfx_popain,   // painsound
    0,    // meleestate
    S_POSS_ATK1,    // missilestate
    S_POSS_DIE1,    // deathstate
    S_POSS_XDIE1,   // xdeathstate
    sfx_podth1,   // deathsound
    8,    // speed
    20*FRACUNIT,    // radius
    56*FRACUNIT,    // height
    100,    // mass
    0,    // damage
    sfx_posact,   // activesound
    MF_SOLID|MF_SHOOTABLE|MF_COUNTKILL   // flags
  },

  {   // MT_SHOTGUY
    9,    // doomednum
    S_SPOS_STND,    // spawnstate
    30,   // spawnhealth
    S_SPOS_RUN1,    // seestate
    sfx_posit2,   // seesound
    8,    // reactiontime
    0,    // attacksound
    S_SPOS_PAIN,    // painstate
    170,    // painchance
    sfx_popain,   // painsound
    0,    // meleestate
    S_SPOS_ATK1,    // missilestate
    S_SPOS_DIE1,    // deathstate
    S_SPOS_XDIE1,   // xdeathstate
    sfx_podth2,   // deathsound
    8,    // speed
    20*FRACUNIT,    // radius
    56*FRACUNIT,    // height
    100,    // mass
    0,    // damage
    sfx_posact,   // activesound
    MF_SOLID|MF_SHOOTABLE|MF_COUNTKILL   // flags
  },

  {   // MT_TROOP
    3001,   // doomednum
    S_TROO_STND,    // spawnstate
    60,   // spawnhealth
    S_TROO_RUN1,    // seestate
    sfx_bgsit1,   // seesound
    8,    // reactiontime
    0,    // attacksound
    S_TROO_PAIN,    // painstate
    200,    // painchance
    sfx_popain,   // painsound
    S_TROO_ATK1,    // meleestate
    S_TROO_ATK1,    // missilestate
    S_TROO_DIE1,    // deathstate
    S_TROO_XDIE1,   // xdeathstate
    sfx_bgdth1,   // deathsound
    8,    // speed
    20*FRACUNIT,    // radius
    56*FRACUNIT,    // height
    100,    // mass
    0,    // damage
    sfx_bgact,    // activesound
    MF_SOLID|MF_SHOOTABLE|MF_COUNTKILL   // flags
  },

  {   // MT_SERGEANT
    3002,   // doomednum
    S_SARG_STND,    // spawnstate
    150,    // spawnhealth
    S_SARG_RUN1,    // seestate
    sfx_sgtsit,   // seesound
    8,    // reactiontime
    sfx_sgtatk,   // attacksound
    S_SARG_PAIN,    // painstate
    180,    // painchance
    sfx_dmpain,   // painsound
    S_SARG_ATK1,    // meleestate
    0,    // missilestate
    S_SARG_DIE1,    // deathstate
    S_NULL,   // xdeathstate
    sfx_sgtdth,   // deathsound
    10,   // speed
    30*FRACUNIT,    // radius
    56*FRACUNIT,    // height
    400,    // mass
    0,    // damage
    sfx_dmact,    // activesound
    MF_SOLID|MF_SHOOTABLE|MF_COUNTKILL   // flags
  },

  {   // MT_SHADOWS
    58,   // doomednum
    S_SARG_STND,    // spawnstate
    150,    // spawnhealth
    S_SARG_RUN1,    // seestate
    sfx_sgtsit,   // seesound
    8,    // reactiontime
    sfx_sgtatk,   // attacksound
    S_SARG_PAIN,    // painstate
    180,    // painchance
    sfx_dmpain,   // painsound
    S_SARG_ATK1,    // meleestate
    0,    // missilestate
    S_SARG_DIE1,    // deathstate
    S_NULL,   // xdeathstate
    sfx_sgtdth,   // deathsound
    10,   // speed
    30*FRACUNIT,    // radius
    56*FRACUNIT,    // height
    400,    // mass
    0,    // damage
    sfx_dmact,    // activesound
    MF_SOLID|MF_SHOOTABLE|MF_SHADOW|MF_COUNTKILL   // flags
  },

  {   // MT_BRUISER
    3003,   // doomednum
    S_BOSS_STND,    // spawnstate
    1000,   // spawnhealth
    S_BOSS_RUN1,    // seestate
    sfx_brssit,   // seesound
    8,    // reactiontime
    0,    // attacksound
    S_BOSS_PAIN,    // painstate
    50,   // painchance
    sfx_dmpain,   // painsound
    S_BOSS_ATK1,    // meleestate
    S_BOSS_ATK1,    // missilestate
    S_BOSS_DIE1,    // deathstate
    S_NULL,   // xdeathstate
    sfx_brsdth,   // deathsound
    8,    // speed
    24*FRACUNIT,    // radius
    64*FRACUNIT,    // height
    1000,   // mass
    0,    // damage
    sfx_dmact,    // activesound
    MF_SOLID|MF_SHOOTABLE|MF_COUNTKILL   // flags
  },

  {   // MT_BRUISERSHOT
    -1,   // doomednum
    S_BRBALL1,    // spawnstate
    1000,   // spawnhealth
    S_NULL,   // seestate
    sfx_firsht,   // seesound
    8,    // reactiontime
    sfx_None,   // attacksound
    S_NULL,   // painstate
    0,    // painchance
    sfx_None,   // painsound
    S_NULL,   // meleestate
    S_NULL,   // missilestate
    S_BRBALLX1,   // deathstate
    S_NULL,   // xdeathstate
    sfx_firxpl,   // deathsound
    15*FRACUNIT,   // speed
    6*FRACUNIT,   // radius
    8*FRACUNIT,   // height
    100,    // mass
    8,    // damage
    sfx_None,   // activesound
    MF_NOBLOCKMAP|MF_MISSILE|MF_DROPOFF|MF_NOGRAVITY   // flags
  },

  {   // MT_BARREL
    2035,   // doomednum
    S_BAR1,   // spawnstate
    20,   // spawnhealth
    S_NULL,   // seestate
    sfx_None,   // seesound
    8,    // reactiontime
    sfx_None,   // attacksound
    S_NULL,   // painstate
    0,    // painchance
    sfx_None,   // painsound
    S_NULL,   // meleestate
    S_NULL,   // missilestate
    S_BEXP,   // deathstate
    S_NULL,   // xdeathstate
    sfx_barexp,   // deathsound
    0,    // speed
    10*FRACUNIT,    // radius
    42*FRACUNIT,    // height
    100,    // mass
    0,    // damage
    sfx_None,   // activesound
    MF_SOLID|MF_SHOOTABLE|MF_NOBLOOD   // flags
  },

  {   // MT_TROOPSHOT
    -1,   // doomednum
    S_TBALL1,   // spawnstate
    1000,   // spawnhealth
    S_NULL,   // seestate
    sfx_firsht,   // seesound
    8,    // reactiontime
    sfx_None,   // attacksound
    S_NULL,   // painstate
    0,    // painchance
    sfx_None,   // painsound
    S_NULL,   // meleestate
    S_NULL,   // missilestate
    S_TBALLX1,    // deathstate
    S_NULL,   // xdeathstate
    sfx_firxpl,   // deathsound
    10*FRACUNIT,    // speed
    6*FRACUNIT,   // radius
    8*FRACUNIT,   // height
    100,    // mass
    3,    // damage
    sfx_None,   // activesound
    MF_NOBLOCKMAP|MF_MISSILE|MF_DROPOFF|MF_NOGRAVITY // flags
  },

  {   // MT_ROCKET
    -1,   // doomednum
    S_ROCKET,   // spawnstate
    1000,   // spawnhealth
    S_NULL,   // seestate
    sfx_None,   // seesound
    8,    // reactiontime
    sfx_None,   // attacksound
    S_NULL,   // painstate
    0,    // painchance
    sfx_None,   // painsound
    S_NULL,   // meleestate
    S_NULL,   // missilestate
    S_EXPLODE1,   // deathstate
    S_NULL,   // xdeathstate
    sfx_barexp,   // deathsound
    20*FRACUNIT,    // speed
    11*FRACUNIT,    // radius
    8*FRACUNIT,   // height
    100,    // mass
    20,   // damage
    sfx_None,   // activesound
    MF_NOBLOCKMAP|MF_MISSILE|MF_DROPOFF|MF_NOGRAVITY   // flags
  },

  {   // MT_PUFF
    -1,   // doomednum
    S_PUFF1,    // spawnstate
    1000,   // spawnhealth
    S_NULL,   // seestate
    sfx_None,   // seesound
    8,    // reactiontime
    sfx_None,   // attacksound
    S_NULL,   // painstate
    0,    // painchance
    sfx_None,   // painsound
    S_NULL,   // meleestate
    S_NULL,   // missilestate
    S_NULL,   // deathstate
    S_NULL,   // xdeathstate
    sfx_None,   // deathsound
    0,    // speed
    20*FRACUNIT,    // radius
    16*FRACUNIT,    // height
    100,    // mass
    0,    // damage
    sfx_None,   // activesound
    MF_NOBLOCKMAP|MF_NOGRAVITY // flags
  },

  {   // MT_BLOOD
    -1,   // doomednum
    S_BLOOD1,   // spawnstate
    1000,   // spawnhealth
    S_NULL,   // seestate
    sfx_None,   // seesound
    8,    // reactiontime
    sfx_None,   // attacksound
    S_NULL,   // painstate
    0,    // painchance
    sfx_None,   // painsound
    S_NULL,   // meleestate
    S_NULL,   // missilestate
    S_NULL,   // deathstate
    S_NULL,   // xdeathstate
    sfx_None,   // deathsound
    0,    // speed
    20*FRACUNIT,    // radius
    16*FRACUNIT,    // height
    100,    // mass
    0,    // damage
    sfx_None,   // activesound
    MF_NOBLOCKMAP    // flags
  },

  {   // MT_TFOG
    -1,   // doomednum
    S_TFOG,   // spawnstate
    1000,   // spawnhealth
    S_NULL,   // seestate
    sfx_None,   // seesound
    8,    // reactiontime
    sfx_None,   // attacksound
    S_NULL,   // painstate
    0,    // painchance
    sfx_None,   // painsound
    S_NULL,   // meleestate
    S_NULL,   // missilestate
    S_NULL,   // deathstate
    S_NULL,   // xdeathstate
    sfx_None,   // deathsound
    0,    // speed
    20*FRACUNIT,    // radius
    16*FRACUNIT,    // height
    100,    // mass
    0,    // damage
    sfx_None,   // activesound
    MF_NOBLOCKMAP|MF_NOGRAVITY // flags
  },

  {   // MT_TELEPORTMAN
    14,   // doomednum
    S_NULL,   // spawnstate
    1000,   // spawnhealth
    S_NULL,   // seestate
    sfx_None,   // seesound
    8,    // reactiontime
    sfx_None,   // attacksound
    S_NULL,   // painstate
    0,    // painchance
    sfx_None,   // painsound
    S_NULL,   // meleestate
    S_NULL,   // missilestate
    S_NULL,   // deathstate
    S_NULL,   // xdeathstate
    sfx_None,   // deathsound
    0,    // speed
    20*FRACUNIT,    // radius
    16*FRACUNIT,    // height
    100,    // mass
    0,    // damage
    sfx_None,   // activesound
    MF_NOBLOCKMAP|MF_NOSECTOR    // flags
  },

  {   // MT_MISC0
    2018,   // doomednum
    S_ARM1,   // spawnstate
    1000,   // spawnhealth
    S_NULL,   // seestate
    sfx_None,   // seesound
    8,    // reactiontime
    sfx_None,   // attacksound
    S_NULL,   // painstate
    0,    // painchance
    sfx_None,   // painsound
    S_NULL,   // meleestate
    S_NULL,   // missilestate
    S_NULL,   // deathstate
    S_NULL,   // xdeathstate
    sfx_None,   // deathsound
    0,    // speed
    20*FRACUNIT,    // radius
    16*FRACUNIT,    // height
    100,    // mass
    0,    // damage
    sfx_None,   // activesound
    MF_SPECIAL   // flags
  },

  {   // MT_MISC1
    2019,   // doomednum
    S_ARM2,   // spawnstate
    1000,   // spawnhealth
    S_NULL,   // seestate
    sfx_None,   // seesound
    8,    // reactiontime
    sfx_None,   // attacksound
    S_NULL,   // painstate
    0,    // painchance
    sfx_None,   // painsound
    S_NULL,   // meleestate
    S_NULL,   // missilestate
    S_NULL,   // deathstate
    S_NULL,   // xdeathstate
    sfx_None,   // deathsound
    0,    // speed
    20*FRACUNIT,    // radius
    16*FRACUNIT,    // height
    100,    // mass
    0,    // damage
    sfx_None,   // activesound
    MF_SPECIAL   // flags
  },

  {   // MT_MISC2
    2014,   // doomednum
    S_BON1,   // spawnstate
    1000,   // spawnhealth
    S_NULL,   // seestate
    sfx_None,   // seesound
    8,    // reactiontime
    sfx_None,   // attacksound
    S_NULL,   // painstate
    0,    // painchance
    sfx_None,   // painsound
    S_NULL,   // meleestate
    S_NULL,   // missilestate
    S_NULL,   // deathstate
    S_NULL,   // xdeathstate
    sfx_None,   // deathsound
    0,    // speed
    20*FRACUNIT,    // radius
    16*FRACUNIT,    // height
    100,    // mass
    0,    // damage
    sfx_None,   // activesound
    MF_SPECIAL|MF_COUNTITEM    // flags
  },

  {   // MT_MISC3
    2015,   // doomednum
    S_BON2,   // spawnstate
    1000,   // spawnhealth
    S_NULL,   // seestate
    sfx_None,   // seesound
    8,    // reactiontime
    sfx_None,   // attacksound
    S_NULL,   // painstate
    0,    // painchance
    sfx_None,   // painsound
    S_NULL,   // meleestate
    S_NULL,   // missilestate
    S_NULL,   // deathstate
    S_NULL,   // xdeathstate
    sfx_None,   // deathsound
    0,    // speed
    20*FRACUNIT,    // radius
    16*FRACUNIT,    // height
    100,    // mass
    0,    // damage
    sfx_None,   // activesound
    MF_SPECIAL|MF_COUNTITEM    // flags
  },

  {   // MT_MISC4
    5,    // doomednum
    S_BKEY,   // spawnstate
    1000,   // spawnhealth
    S_NULL,   // seestate
    sfx_None,   // seesound
    8,    // reactiontime
    sfx_None,   // attacksound
    S_NULL,   // painstate
    0,    // painchance
    sfx_None,   // painsound
    S_NULL,   // meleestate
    S_NULL,   // missilestate
    S_NULL,   // deathstate
    S_NULL,   // xdeathstate
    sfx_None,   // deathsound
    0,    // speed
    20*FRACUNIT,    // radius
    16*FRACUNIT,    // height
    100,    // mass
    0,    // damage
    sfx_None,   // activesound
    MF_SPECIAL    // flags
  },

  {   // MT_MISC5
    13,   // doomednum
    S_RKEY,   // spawnstate
    1000,   // spawnhealth
    S_NULL,   // seestate
    sfx_None,   // seesound
    8,    // reactiontime
    sfx_None,   // attacksound
    S_NULL,   // painstate
    0,    // painchance
    sfx_None,   // painsound
    S_NULL,   // meleestate
    S_NULL,   // missilestate
    S_NULL,   // deathstate
    S_NULL,   // xdeathstate
    sfx_None,   // deathsound
    0,    // speed
    20*FRACUNIT,    // radius
    16*FRACUNIT,    // height
    100,    // mass
    0,    // damage
    sfx_None,   // activesound
    MF_SPECIAL    // flags
  },

  {   // MT_MISC6
    6,    // doomednum
    S_YKEY,   // spawnstate
    1000,   // spawnhealth
    S_NULL,   // seestate
    sfx_None,   // seesound
    8,    // reactiontime
    sfx_None,   // attacksound
    S_NULL,   // painstate
    0,    // painchance
    sfx_None,   // painsound
    S_NULL,   // meleestate
    S_NULL,   // missilestate
    S_NULL,   // deathstate
    S_NULL,   // xdeathstate
    sfx_None,   // deathsound
    0,    // speed
    20*FRACUNIT,    // radius
    16*FRACUNIT,    // height
    100,    // mass
    0,    // damage
    sfx_None,   // activesound
    MF_SPECIAL    // flags
  },

  {   // MT_MISC10
    2011,   // doomednum
    S_STIM,   // spawnstate
    1000,   // spawnhealth
    S_NULL,   // seestate
    sfx_None,   // seesound
    8,    // reactiontime
    sfx_None,   // attacksound
    S_NULL,   // painstate
    0,    // painchance
    sfx_None,   // painsound
    S_NULL,   // meleestate
    S_NULL,   // missilestate
    S_NULL,   // deathstate
    S_NULL,   // xdeathstate
    sfx_None,   // deathsound
    0,    // speed
    20*FRACUNIT,    // radius
    16*FRACUNIT,    // height
    100,    // mass
    0,    // damage
    sfx_None,   // activesound
    MF_SPECIAL   // flags
  },

  {   // MT_MISC11
    2012,   // doomednum
    S_MEDI,   // spawnstate
    1000,   // spawnhealth
    S_NULL,   // seestate
    sfx_None,   // seesound
    8,    // reactiontime
    sfx_None,   // attacksound
    S_NULL,   // painstate
    0,    // painchance
    sfx_None,   // painsound
    S_NULL,   // meleestate
    S_NULL,   // missilestate
    S_NULL,   // deathstate
    S_NULL,   // xdeathstate
    sfx_None,   // deathsound
    0,    // speed
    20*FRACUNIT,    // radius
    16*FRACUNIT,    // height
    100,    // mass
    0,    // damage
    sfx_None,   // activesound
    MF_SPECIAL   // flags
  },

  {   // MT_MISC12
    2013,   // doomednum
    S_SOUL,   // spawnstate
    1000,   // spawnhealth
    S_NULL,   // seestate
    sfx_None,   // seesound
    8,    // reactiontime
    sfx_None,   // attacksound
    S_NULL,   // painstate
    0,    // painchance
    sfx_None,   // painsound
    S_NULL,   // meleestate
    S_NULL,   // missilestate
    S_NULL,   // deathstate
    S_NULL,   // xdeathstate
    sfx_None,   // deathsound
    0,    // speed
    20*FRACUNIT,    // radius
    16*FRACUNIT,    // height
    100,    // mass
    0,    // damage
    sfx_None,   // activesound
    MF_SPECIAL|MF_COUNTITEM    // flags
  },

  {   // MT_INS
    2024,   // doomednum
    S_PINS,   // spawnstate
    1000,   // spawnhealth
    S_NULL,   // seestate
    sfx_None,   // seesound
    8,    // reactiontime
    sfx_None,   // attacksound
    S_NULL,   // painstate
    0,    // painchance
    sfx_None,   // painsound
    S_NULL,   // meleestate
    S_NULL,   // missilestate
    S_NULL,   // deathstate
    S_NULL,   // xdeathstate
    sfx_None,   // deathsound
    0,    // speed
    20*FRACUNIT,    // radius
    16*FRACUNIT,    // height
    100,    // mass
    0,    // damage
    sfx_None,   // activesound
    MF_SPECIAL|MF_COUNTITEM    // flags
  },

  {   // MT_MISC14
    2025,   // doomednum
    S_SUIT,   // spawnstate
    1000,   // spawnhealth
    S_NULL,   // seestate
    sfx_None,   // seesound
    8,    // reactiontime
    sfx_None,   // attacksound
    S_NULL,   // painstate
    0,    // painchance
    sfx_None,   // painsound
    S_NULL,   // meleestate
    S_NULL,   // missilestate
    S_NULL,   // deathstate
    S_NULL,   // xdeathstate
    sfx_None,   // deathsound
    0,    // speed
    20*FRACUNIT,    // radius
    16*FRACUNIT,    // height
    100,    // mass
    0,    // damage
    sfx_None,   // activesound
    MF_SPECIAL   // flags
  },

  {   // MT_MISC15
    2026,   // doomednum
    S_PMAP,   // spawnstate
    1000,   // spawnhealth
    S_NULL,   // seestate
    sfx_None,   // seesound
    8,    // reactiontime
    sfx_None,   // attacksound
    S_NULL,   // painstate
    0,    // painchance
    sfx_None,   // painsound
    S_NULL,   // meleestate
    S_NULL,   // missilestate
    S_NULL,   // deathstate
    S_NULL,   // xdeathstate
    sfx_None,   // deathsound
    0,    // speed
    20*FRACUNIT,    // radius
    16*FRACUNIT,    // height
    100,    // mass
    0,    // damage
    sfx_None,   // activesound
    MF_SPECIAL|MF_COUNTITEM    // flags
  },

  {   // MT_MISC16
    2045,   // doomednum
    S_PVIS,   // spawnstate
    1000,   // spawnhealth
    S_NULL,   // seestate
    sfx_None,   // seesound
    8,    // reactiontime
    sfx_None,   // attacksound
    S_NULL,   // painstate
    0,    // painchance
    sfx_None,   // painsound
    S_NULL,   // meleestate
    S_NULL,   // missilestate
    S_NULL,   // deathstate
    S_NULL,   // xdeathstate
    sfx_None,   // deathsound
    0,    // speed
    20*FRACUNIT,    // radius
    16*FRACUNIT,    // height
    100,    // mass
    0,    // damage
    sfx_None,   // activesound
    MF_SPECIAL|MF_COUNTITEM    // flags
  },

  {   // MT_CLIP
    2007,   // doomednum
    S_CLIP,   // spawnstate
    1000,   // spawnhealth
    S_NULL,   // seestate
    sfx_None,   // seesound
    8,    // reactiontime
    sfx_None,   // attacksound
    S_NULL,   // painstate
    0,    // painchance
    sfx_None,   // painsound
    S_NULL,   // meleestate
    S_NULL,   // missilestate
    S_NULL,   // deathstate
    S_NULL,   // xdeathstate
    sfx_None,   // deathsound
    0,    // speed
    20*FRACUNIT,    // radius
    16*FRACUNIT,    // height
    100,    // mass
    0,    // damage
    sfx_None,   // activesound
    MF_SPECIAL   // flags
  },

  {   // MT_MISC17
    2048,   // doomednum
    S_AMMO,   // spawnstate
    1000,   // spawnhealth
    S_NULL,   // seestate
    sfx_None,   // seesound
    8,    // reactiontime
    sfx_None,   // attacksound
    S_NULL,   // painstate
    0,    // painchance
    sfx_None,   // painsound
    S_NULL,   // meleestate
    S_NULL,   // missilestate
    S_NULL,   // deathstate
    S_NULL,   // xdeathstate
    sfx_None,   // deathsound
    0,    // speed
    20*FRACUNIT,    // radius
    16*FRACUNIT,    // height
    100,    // mass
    0,    // damage
    sfx_None,   // activesound
    MF_SPECIAL   // flags
  },

  {   // MT_MISC18
    2010,   // doomednum
    S_ROCK,   // spawnstate
    1000,   // spawnhealth
    S_NULL,   // seestate
    sfx_None,   // seesound
    8,    // reactiontime
    sfx_None,   // attacksound
    S_NULL,   // painstate
    0,    // painchance
    sfx_None,   // painsound
    S_NULL,   // meleestate
    S_NULL,   // missilestate
    S_NULL,   // deathstate
    S_NULL,   // xdeathstate
    sfx_None,   // deathsound
    0,    // speed
    20*FRACUNIT,    // radius
    16*FRACUNIT,    // height
    100,    // mass
    0,    // damage
    sfx_None,   // activesound
    MF_SPECIAL   // flags
  },

  {   // MT_MISC19
    2046,   // doomednum
    S_BROK,   // spawnstate
    1000,   // spawnhealth
    S_NULL,   // seestate
    sfx_None,   // seesound
    8,    // reactiontime
    sfx_None,   // attacksound
    S_NULL,   // painstate
    0,    // painchance
    sfx_None,   // painsound
    S_NULL,   // meleestate
    S_NULL,   // missilestate
    S_NULL,   // deathstate
    S_NULL,   // xdeathstate
    sfx_None,   // deathsound
    0,    // speed
    20*FRACUNIT,    // radius
    16*FRACUNIT,    // height
    100,    // mass
    0,    // damage
    sfx_None,   // activesound
    MF_SPECIAL   // flags
  },

  {   // MT_MISC22
    2008,   // doomednum
    S_SHEL,   // spawnstate
    1000,   // spawnhealth
    S_NULL,   // seestate
    sfx_None,   // seesound
    8,    // reactiontime
    sfx_None,   // attacksound
    S_NULL,   // painstate
    0,    // painchance
    sfx_None,   // painsound
    S_NULL,   // meleestate
    S_NULL,   // missilestate
    S_NULL,   // deathstate
    S_NULL,   // xdeathstate
    sfx_None,   // deathsound
    0,    // speed
    20*FRACUNIT,    // radius
    16*FRACUNIT,    // height
    100,    // mass
    0,    // damage
    sfx_None,   // activesound
    MF_SPECIAL   // flags
  },

  {   // MT_MISC23
    2049,   // doomednum
    S_SBOX,   // spawnstate
    1000,   // spawnhealth
    S_NULL,   // seestate
    sfx_None,   // seesound
    8,    // reactiontime
    sfx_None,   // attacksound
    S_NULL,   // painstate
    0,    // painchance
    sfx_None,   // painsound
    S_NULL,   // meleestate
    S_NULL,   // missilestate
    S_NULL,   // deathstate
    S_NULL,   // xdeathstate
    sfx_None,   // deathsound
    0,    // speed
    20*FRACUNIT,    // radius
    16*FRACUNIT,    // height
    100,    // mass
    0,    // damage
    sfx_None,   // activesound
    MF_SPECIAL   // flags
  },

  {   // MT_MISC24
    8,    // doomednum
    S_BPAK,   // spawnstate
    1000,   // spawnhealth
    S_NULL,   // seestate
    sfx_None,   // seesound
    8,    // reactiontime
    sfx_None,   // attacksound
    S_NULL,   // painstate
    0,    // painchance
    sfx_None,   // painsound
    S_NULL,   // meleestate
    S_NULL,   // missilestate
    S_NULL,   // deathstate
    S_NULL,   // xdeathstate
    sfx_None,   // deathsound
    0,    // speed
    20*FRACUNIT,    // radius
    16*FRACUNIT,    // height
    100,    // mass
    0,    // damage
    sfx_None,   // activesound
    MF_SPECIAL   // flags
  },

  {   // MT_CHAINGUN
    2002,   // doomednum
    S_MGUN,   // spawnstate
    1000,   // spawnhealth
    S_NULL,   // seestate
    sfx_None,   // seesound
    8,    // reactiontime
    sfx_None,   // attacksound
    S_NULL,   // painstate
    0,    // painchance
    sfx_None,   // painsound
    S_NULL,   // meleestate
    S_NULL,   // missilestate
    S_NULL,   // deathstate
    S_NULL,   // xdeathstate
    sfx_None,   // deathsound
    0,    // speed
    20*FRACUNIT,    // radius
    16*FRACUNIT,    // height
    100,    // mass
    0,    // damage
    sfx_None,   // activesound
    MF_SPECIAL   // flags
  },

  {   // MT_MISC26
    2005,   // doomednum
    S_CSAW,   // spawnstate
    1000,   // spawnhealth
    S_NULL,   // seestate
    sfx_None,   // seesound
    8,    // reactiontime
    sfx_None,   // attacksound
    S_NULL,   // painstate
    0,    // painchance
    sfx_None,   // painsound
    S_NULL,   // meleestate
    S_NULL,   // missilestate
    S_NULL,   // deathstate
    S_NULL,   // xdeathstate
    sfx_None,   // deathsound
    0,    // speed
    20*FRACUNIT,    // radius
    16*FRACUNIT,    // height
    100,    // mass
    0,    // damage
    sfx_None,   // activesound
    MF_SPECIAL   // flags
  },

  {   // MT_MISC27
    2003,   // doomednum
    S_LAUN,   // spawnstate
    1000,   // spawnhealth
    S_NULL,   // seestate
    sfx_None,   // seesound
    8,    // reactiontime
    sfx_None,   // attacksound
    S_NULL,   // painstate
    0,    // painchance
    sfx_None,   // painsound
    S_NULL,   // meleestate
    S_NULL,   // missilestate
    S_NULL,   // deathstate
    S_NULL,   // xdeathstate
    sfx_None,   // deathsound
    0,    // speed
    20*FRACUNIT,    // radius
    16*FRACUNIT,    // height
    100,    // mass
    0,    // damage
    sfx_None,   // activesound
    MF_SPECIAL   // flags
  },

  {   // MT_SHOTGUN
    2001,   // doomednum
    S_SHOT,   // spawnstate
    1000,   // spawnhealth
    S_NULL,   // seestate
    sfx_None,   // seesound
    8,    // reactiontime
    sfx_None,   // attacksound
    S_NULL,   // painstate
    0,    // painchance
    sfx_None,   // painsound
    S_NULL,   // meleestate
    S_NULL,   // missilestate
    S_NULL,   // deathstate
    S_NULL,   // xdeathstate
    sfx_None,   // deathsound
    0,    // speed
    20*FRACUNIT,    // radius
    16*FRACUNIT,    // height
    100,    // mass
    0,    // damage
    sfx_None,   // activesound
    MF_SPECIAL   // flags
  },

  {   // MT_MISC31
    2028,   // doomednum
    S_COLU,   // spawnstate
    1000,   // spawnhealth
    S_NULL,   // seestate
    sfx_None,   // seesound
    8,    // reactiontime
    sfx_None,   // attacksound
    S_NULL,   // painstate
    0,    // painchance
    sfx_None,   // painsound
    S_NULL,   // meleestate
    S_NULL,   // missilestate
    S_NULL,   // deathstate
    S_NULL,   // xdeathstate
    sfx_None,   // deathsound
    0,    // speed
    16*FRACUNIT,    // radius
    16*FRACUNIT,    // height
    100,    // mass
    0,    // damage
    sfx_None,   // activesound
    MF_SOLID   // flags
  },

  {   // MT_MISC43
    46,   // doomednum
    S_REDTORCH,   // spawnstate
    1000,   // spawnhealth
    S_NULL,   // seestate
    sfx_None,   // seesound
    8,    // reactiontime
    sfx_None,   // attacksound
    S_NULL,   // painstate
    0,    // painchance
    sfx_None,   // painsound
    S_NULL,   // meleestate
    S_NULL,   // missilestate
    S_NULL,   // deathstate
    S_NULL,   // xdeathstate
    sfx_None,   // deathsound
    0,    // speed
    16*FRACUNIT,    // radius
    16*FRACUNIT,    // height
    100,    // mass
    0,    // damage
    sfx_None,   // activesound
    MF_SOLID   // flags
  },

  {   // MT_MISC48
    48,   // doomednum
    S_TECHPILLAR,   // spawnstate
    1000,   // spawnhealth
    S_NULL,   // seestate
    sfx_None,   // seesound
    8,    // reactiontime
    sfx_None,   // attacksound
    S_NULL,   // painstate
    0,    // painchance
    sfx_None,   // painsound
    S_NULL,   // meleestate
    S_NULL,   // missilestate
    S_NULL,   // deathstate
    S_NULL,   // xdeathstate
    sfx_None,   // deathsound
    0,    // speed
    16*FRACUNIT,    // radius
    16*FRACUNIT,    // height
    100,    // mass
    0,    // damage
    sfx_None,   // activesound
    MF_SOLID   // flags
  },

  {   // MT_MISC49
    34,   // doomednum
    S_CANDLESTIK,   // spawnstate
    1000,   // spawnhealth
    S_NULL,   // seestate
    sfx_None,   // seesound
    8,    // reactiontime
    sfx_None,   // attacksound
    S_NULL,   // painstate
    0,    // painchance
    sfx_None,   // painsound
    S_NULL,   // meleestate
    S_NULL,   // missilestate
    S_NULL,   // deathstate
    S_NULL,   // xdeathstate
    sfx_None,   // deathsound
    0,    // speed
    20*FRACUNIT,    // radius
    16*FRACUNIT,    // height
    100,    // mass
    0,    // damage
    sfx_None,   // activesound
    0    // flags
  },

  {   // MT_MISC50
    35,   // doomednum
    S_CANDELABRA,   // spawnstate
    1000,   // spawnhealth
    S_NULL,   // seestate
    sfx_None,   // seesound
    8,    // reactiontime
    sfx_None,   // attacksound
    S_NULL,   // painstate
    0,    // painchance
    sfx_None,   // painsound
    S_NULL,   // meleestate
    S_NULL,   // missilestate
    S_NULL,   // deathstate
    S_NULL,   // xdeathstate
    sfx_None,   // deathsound
    0,    // speed
    16*FRACUNIT,    // radius
    16*FRACUNIT,    // height
    100,    // mass
    0,    // damage
    sfx_None,   // activesound
    MF_SOLID   // flags
  },

  {   // MT_MISC62
    15,   // doomednum
    S_PLAY_DIE7,    // spawnstate
    1000,   // spawnhealth
    S_NULL,   // seestate
    sfx_None,   // seesound
    8,    // reactiontime
    sfx_None,   // attacksound
    S_NULL,   // painstate
    0,    // painchance
    sfx_None,   // painsound
    S_NULL,   // meleestate
    S_NULL,   // missilestate
    S_NULL,   // deathstate
    S_NULL,   // xdeathstate
    sfx_None,   // deathsound
    0,    // speed
    20*FRACUNIT,    // radius
    16*FRACUNIT,    // height
    100,    // mass
    0,    // damage
    sfx_None,   // activesound
    0    // flags
  },

  {   // MT_MISC68
    10,   // doomednum
    S_PLAY_XDIE9,   // spawnstate
    1000,   // spawnhealth
    S_NULL,   // seestate
    sfx_None,   // seesound
    8,    // reactiontime
    sfx_None,   // attacksound
    S_NULL,   // painstate
    0,    // painchance
    sfx_None,   // painsound
    S_NULL,   // meleestate
    S_NULL,   // missilestate
    S_NULL,   // deathstate
    S_NULL,   // xdeathstate
    sfx_None,   // deathsound
    0,    // speed
    20*FRACUNIT,    // radius
    16*FRACUNIT,    // height
    100,    // mass
    0,    // damage
    sfx_None,   // activesound
    0    // flags
  },

  {   // MT_MISC69
    12,   // doomednum
    S_PLAY_XDIE9,   // spawnstate
    1000,   // spawnhealth
    S_NULL,   // seestate
    sfx_None,   // seesound
    8,    // reactiontime
    sfx_None,   // attacksound
    S_NULL,   // painstate
    0,    // painchance
    sfx_None,   // painsound
    S_NULL,   // meleestate
    S_NULL,   // missilestate
    S_NULL,   // deathstate
    S_NULL,   // xdeathstate
    sfx_None,   // deathsound
    0,    // speed
    20*FRACUNIT,    // radius
    16*FRACUNIT,    // height
    100,    // mass
    0,    // damage
    sfx_None,   // activesound
    0    // flags
  },

  {   // MT_MISC71
    24,   // doomednum
    S_GIBS,   // spawnstate
    1000,   // spawnhealth
    S_NULL,   // seestate
    sfx_None,   // seesound
    8,    // reactiontime
    sfx_None,   // attacksound
    S_NULL,   // painstate
    0,    // painchance
    sfx_None,   // painsound
    S_NULL,   // meleestate
    S_NULL,   // missilestate
    S_NULL,   // deathstate
    S_NULL,   // xdeathstate
    sfx_None,   // deathsound
    0,    // speed
    20*FRACUNIT,    // radius
    16*FRACUNIT,    // height
    100,    // mass
    0,    // damage
    sfx_None,   // activesound
    0    // flags
  }

};
